modLoader="javafml"
loaderVersion="${loader_version_range}"
license="${mod_license}"
issueTrackerURL="https://github.com/"

[[mods]]
modId="${mod_id}"
version="${mod_version}"
displayName="${mod_name}"
authors="${mod_authors}"
credits="${mod_credits}"
description='''${mod_description}'''
logoFile="exbingo/icon.png"

[[mixins]]
config="mixins.bingo.json"

[[mixins]]
config="mixins-client.bingo.json"

[[dependencies.${mod_id}]]
modId="neoforge"
type="required"
versionRange="${neo_version_range}"
ordering="NONE"
side="BOTH"

[[dependencies.${mod_id}]]
modId="minecraft"
type="required"
versionRange="${minecraft_version_range}"
ordering="NONE"
side="BOTH"

[[dependencies.${mod_id}]]
modId="jei"
type="optional"
ordering="AFTER"
side="CLIENT"

[[dependencies.${mod_id}]]
modId="voicechat"
type="optional"
ordering="AFTER"
side="BOTH"
